# Generated by Django 6.0.2 on 2026-03-20 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
